#!/usr/bin/env python

from predict import MODEL_ID, LORA_MODEL_ID, LORA_FILE_NAME, MODEL_CACHE
import os
import shutil
import sys

import torch
from diffusers import StableDiffusionPipeline
from huggingface_hub import hf_hub_download

# append project directory to path so predict.py can be imported
sys.path.append('.')


if os.path.exists(MODEL_CACHE):
    shutil.rmtree(MODEL_CACHE)
os.makedirs(MODEL_CACHE, exist_ok=True)


pipe = StableDiffusionPipeline.from_pretrained(
    MODEL_ID,
    cache_dir=MODEL_CACHE,
    torch_dtype=torch.float16
)

hf_hub_download(
    repo_id=LORA_MODEL_ID,
    filename=LORA_FILE_NAME,
    local_dir=MODEL_CACHE,
    cache_dir=MODEL_CACHE,
)
